export const elements = {
  repoSelect: document.getElementById('repo-select') as HTMLSelectElement,
  repoSelectorGroup: document.querySelector('.repo-selector-group') as HTMLElement,
  emptyState: document.getElementById('empty-state') as HTMLElement,
  branchSelect: document.getElementById('branch-select') as HTMLSelectElement,
  authorSelect: document.getElementById('author-select') as HTMLSelectElement,
  datePresetSelect: document.getElementById('date-preset-select') as HTMLSelectElement,
  dateRangeGroup: document.querySelector('.date-range-group') as HTMLElement,
  sinceDate: document.getElementById('since-date') as HTMLInputElement,
  untilDate: document.getElementById('until-date') as HTMLInputElement,
  searchInput: document.getElementById('search-input') as HTMLInputElement,
  resetBtn: document.getElementById('reset-btn') as HTMLButtonElement,
  loadingOverlay: document.getElementById('loading') as HTMLElement,
  errorBanner: document.getElementById('error-message') as HTMLElement,
  commitsTbody: document.getElementById('commits-tbody') as HTMLElement,
  graphSvg: document.getElementById('graph-svg') as any, // SVGElement
  tableContainer: document.querySelector('.list-pane') as HTMLElement,
  
  detailsPane: document.getElementById('details-pane') as HTMLElement,
  resizerBar: document.getElementById('resizer-bar') as HTMLElement,
  detailsCloseBtn: document.getElementById('details-close-btn') as HTMLButtonElement,
  detailsPlaceholder: document.getElementById('details-placeholder') as HTMLElement,
  detailsContent: document.getElementById('details-content') as HTMLElement,
  detailHashBadge: document.getElementById('detail-hash-badge') as HTMLElement,
  detailMergeBadge: document.getElementById('detail-merge-badge') as HTMLElement,
  detailAuthorAvatar: document.getElementById('detail-author-avatar') as HTMLElement,
  detailAuthorName: document.getElementById('detail-author-name') as HTMLElement,
  detailAuthorDate: document.getElementById('detail-author-date') as HTMLElement,
  detailMsgSubject: document.getElementById('detail-msg-subject') as HTMLElement,
  detailMsgBody: document.getElementById('detail-msg-body') as HTMLElement,
  detailStatsRow: document.getElementById('detail-stats-row') as HTMLElement,
  detailFilesTree: document.getElementById('detail-files-tree') as HTMLElement,
  leftPaneEl: document.querySelector('.left-pane') as HTMLElement,
  mainLayoutEl: document.querySelector('.main-layout') as HTMLElement,
  selectionHistoryEl: document.getElementById('selection-history') as HTMLElement,
  fileHistoryEl: document.getElementById('file-history') as HTMLElement,

  statsStrip: document.getElementById('stats-strip') as HTMLElement,
  stripCommitsVal: document.getElementById('strip-commits-val') as HTMLElement,
  stripAdd: document.getElementById('strip-add') as HTMLElement,
  stripDel: document.getElementById('strip-del') as HTMLElement,
  stripContributorsVal: document.getElementById('strip-contributors-val') as HTMLElement,
  stripRange: document.getElementById('strip-range') as HTMLElement,
  statsToggleBtn: document.getElementById('stats-toggle-btn') as HTMLButtonElement,
  overviewStats: document.getElementById('overview-stats') as HTMLElement,
  overviewRange: document.getElementById('overview-range') as HTMLElement,
  ovCommits: document.getElementById('ov-commits') as HTMLElement,
  ovAdd: document.getElementById('ov-add') as HTMLElement,
  ovDel: document.getElementById('ov-del') as HTMLElement,
  activitySvg: document.getElementById('activity-svg') as any, // SVGElement
  contributorsList: document.getElementById('contributors-list') as HTMLElement,
  topFilesList: document.getElementById('top-files-list') as HTMLElement,
  authorStatsPane: document.getElementById('author-stats') as HTMLElement,
  authorStatsAvatar: document.getElementById('author-stats-avatar') as HTMLElement,
  authorStatsName: document.getElementById('author-stats-name') as HTMLElement,
  authorStatsEmail: document.getElementById('author-stats-email') as HTMLElement,
  auCommits: document.getElementById('au-commits') as HTMLElement,
  auAdd: document.getElementById('au-add') as HTMLElement,
  auDel: document.getElementById('au-del') as HTMLElement,
  weekdayChart: document.getElementById('weekday-chart') as HTMLElement,
  authorTopFiles: document.getElementById('author-top-files') as HTMLElement,
  authorHighlightBtn: document.getElementById('author-highlight-btn') as HTMLButtonElement,
};
